adafruit/tinyuf2

.github/workflows/build.yml, .gitmodules
add esp-idf as submodule (same version used by circuitpython), due to the fact that esp-idf latest changes too often with file re-org. While most changes needed by bootloader is not needed.
=> Fix esp32s2 ci

ports/esp32s2/components/bootloader/subproject/main/bootloader_start.c
Added support for PIN_APA102 and PIN_LED in the ESP32S2 2nd stage bootloader. Both illuminate during the checking time for the UF2 button. Tested on the UnexpectedMaker FeatherS2.
=> Add PIN_APA102 and PIN_LED support to 2nd stage bootloader

ports/esp32s2/Makefile, ports/esp32s2/boards/adafruit_magtag_29gray/board.h, ports/esp32s2/boards/adafruit_metro_esp32s2/board.h, ports/esp32s2/boards/boards.c, ports/esp32s2/boards/boards.h, ports/esp32s2/boards/espressif_kaluga_1/board.h, ports/esp32s2/boards/espressif_saola_1_wroom/board.h, ports/esp32s2/boards/espressif_saola_1_wrover/board.h, ports/esp32s2/boards/microdev_micro_s2/board.h, ports/esp32s2/boards/unexpectedmaker_feathers2/board.h, ports/esp32s2/components/bootloader/subproject/main/bootloader_start.c
- add NEOPIXEL_ENABLE_PIN for magtag
- Use all 4 neopixels on magtag for indicator in both tinyuf2 and 2nd stage bootloader
- add LED_STATE_ON macro
- rename bunch of macros
- refactor and clean up code.
=> Enhance Magtag indicator

ports/stm32f4/boards.c
Will trying to port this to some f401 boards I have, I was having a hard time getting logging working. I finally tracked this down to the UART not being fully initialized on startup. This seemed to do it.
Still tracking down the remaining issues, but at least have logs now!
=> Initialize UART fully for logging.

.github/workflows/build.yml, ports/stm32f4/board_flash.c, ports/stm32f4/boards.c, ports/stm32f4/boards/feather_stm32f405_express/board.h, ports/stm32f4/boards/stm32f401_blackpill/board.h, ports/stm32f4/boards/stm32f401_blackpill/board.mk, ports/stm32f4/boards/stm32f411ve_discovery/board.h, ports/stm32f4/linker/stm32f4.ld
Got this working on some cheap stm32f401 boards I found on amazon: https://www.amazon.com/SongHe-STM32F401-Development-STM32F401CCU6-Learning/dp/B07XBWGF9M
Doing so required some tweaks:
* Drop RAM listed in the linker script, to account for 64KB SRAM in stm32f401xB/xC. This *should* still work on boards w/ more SRAM, but I don't have one on which to test.
* The VBUS sense pin isn't wired on these, so adding the ability to add a define to have the firmware skip that setup, and properly setup the USB to not do VBUS sensing.
* To fully run my application, (Zephyr based) I added code to de-init the peripherals and timers to the app jump code.
* Only define the `BOARD_FLASH_SECTORS` with a default value of `8` if one isn't set by the board. This let me set this to the proper value of `6` for …
=> Various stm32f4 improvements, add stm32f401 blackpill board

.github/workflows/build.yml
fix #61 
- `update-tinyuf2` is uploaded separately in release assets. 
- The zip file still contains the `update-uf2` as it is before.
- build artifact does not include update-uf2 since it is zipped anyway.
=> Release update uf2 seperately

src/ghostfat.c
Added date of compiled to INFO_UF2.TXT
```
TinyUF2 Bootloader 0.2.1-20-g3811298-dirty - esp-idf (v4.3-dev-1197-g8bc19ba89) tinyusb (0.7.0-45-g4a2baf40)
Model: Espressif Saola 1R WROVER
Board-ID: ESP32S2-Saola1R-v1.2
Date: Feb 17 2021
```
=> add date to INFO_UF2.TXT

src/ghostfat.c, src/uf2.h
Add support for multiple sectors per cluster in GhostFAT to enable larger flash sizes.
=> Add support for multiple sectors per cluster in GhostFAT

ports/esp32s2/Makefile, ports/esp32s2/boards/board_flash.c, src/board_api.h, src/msc.c, src/screen.c
- Esp32s2 increase flash cache from 4K to 64KB. This allow esp to use block erase instead of sector erase and gain 2x
speed flashing
- Also skip erase & write if contents already matches.
```
Before PR
written 1249536 bytes in 19.38 seconds.
Speed : 64.48 KB/s
After PR
written 1249536 bytes in 9.69 seconds.
Speed : 128.95 KB/s
```
=> Speedup esp32 flash

ports/esp32s2/boards/adafruit_funhouse_esp32s2/board.h, ports/esp32s2/boards/adafruit_magtag_29gray/board.h, ports/esp32s2/boards/boards.c, ports/esp32s2/components/bootloader/subproject/main/bootloader_start.c
notice some changes in revB schematics and update board file accordingly
1. Pin double reset RC change from 42 to 38
2. There is no `DOTSTAR_PIN_PWR`
3. Dispaly CS, DC, RST is all +1
4. TODO need new PID for funhouse
=> update funhouse to match revB

src/compile_date.h, src/ghostfat.c
This is to simplify the process of generating repeatable ghostfat images from tests.
Supporting this will help automate validation that the resulting image files are unchanged.
=> Allow overriding the compilation date/time

ports/mimxrt10xx/Makefile
On my Linux system, "uname -i" just prints "unknown". "uname -m" prints "x86_64".
=> Correct detecting the right sdphost binary for linux

ports/mimxrt10xx/boards/metro_m7_1011/board.h, ports/mimxrt10xx/boards/metro_m7_1011/flash_config.c
& change product to match CircuitPython.  @ladyada I'm not sure whether it's this or a change in CircuitPython that is needed to fix copying CIRCUITPY content more than 1MB..
=> metro m7: Switch bootloader to 4MB flash part

ports/mimxrt10xx/README.md, ports/mimxrt10xx/board_flash.c, src/board_api.h
Use bootmode from SRC->SBMR2 to determine whether we are in Serial Download mode. If so write the tinyuf2 image to flash. So basically everytime SDPHost is uesd, it will write contents to flash. This works better as 
- recovery method or when reworking components swapping mcu and/or flash chip. 
- prototyping/simulate other boards e.g using evk board without actually drag & drop uf2 once loaded via SDP
- At worse, user load SDP with the same image on flash, the write caching will compare with existing contents and won't perform any erase/write op.
@nxf58843 @gsteiert would you mind reviewing the PR, also please accept the contributor invitation, it make requesting you as reviewer much easier in the future
=> Rt1010 sdphost always write to flash

.github/workflows/build.yml, erase_firmware/erase_firmware.c, ports/esp32s2/boards/boards.c, ports/lpc55/boards.c, ports/lpc55/erase_firmware/Makefile, ports/make.mk, ports/mimxrt10xx/Makefile, ports/mimxrt10xx/board_flash.c, ports/mimxrt10xx/boards.c, ports/mimxrt10xx/boards/imxrt1010_evk/board.h, ports/mimxrt10xx/boards/imxrt1020_evk/bl_api.c, ports/mimxrt10xx/boards/imxrt1020_evk/board.h, ports/mimxrt10xx/boards/imxrt1060_evk/bl_api.h, ports/mimxrt10xx/boards/imxrt1060_evk/board.h, ports/mimxrt10xx/erase_firmware/Makefile, ports/mimxrt10xx/erase_firmware/memory.ld, ports/mimxrt10xx/port.mk, ports/stm32f3/board_flash.c, ports/stm32f3/boards.c, ports/stm32f3/erase_firmware/Makefile, ports/stm32f4/board_flash.c, ports/stm32f4/boards.c, ports/stm32f4/erase_firmware/Makefile, ports/template_port/board_flash.c, ports/template_port/boards.c, src/board_api.h, src/ghostfat.c, src/main.c, src/usb_descriptors.c
This PR fix #95  
- ground work for `erase_firmware-BOARD.uf2` for all ports
- new board API: board_reset() and board_flash_erase_app()
- add erase_firmware as std application that reset board with MAGIC ERASE_APP
- IMXRT implement board_flash_erase_app() add makefile to support erase_firmware. For iMXRT it is much quicker to perform chip erase and re-write bootloader from sram to flash. (sector/block erase probably takes longer).
- `erase_firmware-BOARD.uf2` is also uploaded as ci artifact/release if available.
- Also update tinyusb to latest as well (why not).
=> Add Imxrt erase firmware

.github/workflows/build.yml, ports/mimxrt10xx/board_flash.c
When starting with a blank flash chip, the board will enter sdp bootloader mode even if the jumpers are in the FlexSPI boot position.  However, since b28b83a24990624961b1af80be8257a91e24f14e, tinyuf2 would not write itself to flash in this situation. Make it do so in both the "boot switch" or "fcfb invalid" cases.
=> mimxrt10xx: Also self-install when FCFB not valid

ports/esp32s2/components/bootloader/subproject/main/bootloader_start.c
reset reason for esp_restart() changed with recent IDF. This fix request to uf2 bootloader. related to #128 
@T94T would you mind trying this out.
=> fix esp32s2 request to uf2 using reset hint

ports/esp32s2/boards/unexpectedmaker_feathers2_neo/board.h
As per title - I forgot to add the status LED
=> Added IO13 Status LED on the FeatherS2 Neo

ports/esp32s2/boards/boards.c, ports/esp32s2/boards/espressif_hmi_1/board.h
Added support for onboard neopixel that has its power control via the TCA9554
=> Add TCA9554 peripheral power control for neopixel support

ports/esp32s2/Makefile, ports/esp32s2/boards/espressif_hmi_1/board.h, ports/esp32s2/components/bootloader/subproject/main/bootloader_start.c
Added support for I2C TCA9554 peripheral power control during the boot2 phase.
Uses software I2C. 
Made a small change to the neopixel reset timing (increased to 1000usec) as it seems to be needed on this board.
I tested this timing with another neopixel equipped board (Gravitech Cucumber) and it worked.
=> Added support for I2C power control during boot2 phase

ports/stm32f4/boards.c
This branch has been tested successfully on a Nucleo F412ZG board (144 pins!) and on custom boards with F412CE (only 48 pins). It will also help to support boards with F413, F423, F446, F469 and F479.
=> add support for stm32f412

ports/stm32f4/board_flash.c
Bug symptom: if an image for stm32f4 begins with >=256 bytes that already match flash content then the image must be written twice.
Reason: if the first flash_write() into an erase block matches flash content, the erase is delayed and will destroy that matching content later.
=> fix board_flash_write() on stm32f4

ports/mimxrt10xx/Makefile, ports/mimxrt10xx/apps/memory.ld, ports/mimxrt10xx/linker/MIMXRT1011_ram.ld, ports/mimxrt10xx/linker/MIMXRT1021_ram.ld, ports/mimxrt10xx/linker/MIMXRT1024_ram.ld, ports/mimxrt10xx/linker/MIMXRT1062_ram.ld, ports/mimxrt10xx/linker/MIMXRT1064_ram.ld, ports/mimxrt10xx/linker/memory.ld
- use `sed` to extract SDP_WRITE_ADDR (_fcfb_origin) and SDP_JUMP_ADDR (_ivt_origin) from linker file. 
- This helps to reduce the amount of manual work and magic number should we make changes to linker file.
=> extract SDP_WRITE_ADDR (_fcfb_origin) and SDP_JUMP_ADDR (_ivt_origin) from linker file

ports/mimxrt10xx/Makefile, ports/mimxrt10xx/README.md, ports/mimxrt10xx/sdphost/sdphost.md
This pull request removes the OS checking for sdphost and instructs the user to install the NXP SPSDK from PyPI.
The directory with with sdphost binaries has a note that it is being depricated and where to find SPSDK.
Most of the edits are in mimxrt10xx/README.md 
Let me know if anything is unclear.
=> NXP SPSDK for MIMXRT builds

ports/espressif/components/bootloader/subproject/main/bootloader_start.c
fix double tap issue, fix #176 . Root cause: `gpio_ll_set_level()` is used in version 0.7.0 since S3 gpio rom does not have `gpio_output_set_high()`, unlike rom API, gpio_ll needs to explicitly enable output first.
@ladyada while working on this issue, I figured out that `esp_rom_gpio_pad_select_gpio()` can also be used to get JTAG pin working as double tap pin. Therefore there is no restriction on JTAG pin after this got merged. Please skip 0.7.0 for new S2 board, 0.8.0 will be released as soon as this is merged.
=> fix double tap issue

.github/workflows/build_esp32.yml, ports/espressif/Makefile
`combined.bin` for S3 has different bootloader.bin offset (0x0 vs 0x1000 in S2). This PR fixes combined.bin generation for S3.
@ladyada
=> Fix combined bin generation for S3

.github/workflows/build_arm.yml, ports/stm32f4/boards/sparkfun_stm32_thing_plus/board.h, ports/stm32f4/boards/sparkfun_stm32_thing_plus/board.mk
Hi,
Please consider accepting this MR which adds support for [SparkFun's Thing Plus STM32](https://www.sparkfun.com/products/17712) board. The USB VID and PID values were provided by SparkFun and are already in [CircuitPython](https://github.com/adafruit/circuitpython/blob/main/ports/stm/boards/sparkfun_stm32_thing_plus/mpconfigboard.mk)'s definition for this board.
Tested by using TinyUF2 to install CircuitPython 7.2.0 (alpha) to my own board.
Thanks!
=> Support sparkfun thing plus stm32

.github/workflows/build_esp32.yml, ports/espressif/README.md, ports/espressif/boards/lilygo_ttgo_t8_s2/board.cmake, ports/espressif/boards/lilygo_ttgo_t8_s2/board.h, ports/espressif/boards/lilygo_ttgo_t8_s2/sdkconfig
=> Add LilyGo TTGO T8 ESP32-S2

.github/workflows/build_esp32.yml, ports/espressif/README.md, ports/espressif/boards/lilygo_ttgo_t8_s2_wroom/board.cmake, ports/espressif/boards/lilygo_ttgo_t8_s2_wroom/board.h, ports/espressif/boards/lilygo_ttgo_t8_s2_wroom/sdkconfig
=> Add LilyGo TTGO T8 ESP32-S2-WROOM

ports/stm32f4/boards.c, ports/stm32f4/boards/feather_stm32f405_express/board.h, ports/stm32f4/boards/sparkfun_stm32_thing_plus/board.h, ports/stm32f4/boards/stm32f401_blackpill/board.h, ports/stm32f4/boards/stm32f411ce_blackpill/board.h, ports/stm32f4/boards/stm32f411ve_discovery/board.h
...by defining NEOPIXEL_ NUMBER which now acts on values bigger than 1. Furthermore users can define a custom pin mode for the output pin, e.g. open-drain for applications where an pull-up resistor is used as a 3.3V to 5V logic level shifter.
This feature is handy for e.g. stm32f4 keyboards that have long external sk6812/ws2812 chains which can be used together with tinyuf2.
=> [STM32F4] Allow user defined amount of Neopixels as status indicator

ports/stm32f3/boards.h, ports/stm32f4/boards.h
With this PR we can set a custom application start in "board.h":
`#define BOARD_FLASH_APP_START 0x08020000`
The default start vectors are still 0x08004000 on stm32f3 and 0x08010000 on stm32f4.
Other common start vectors on stm32f4 are 0x08008000 and 0x08020000.
A script or makefile of another project can set the app start like that:
`CFLAGS="-DBOARD_FLASH_APP_START=0x08004000" make -C <path-to-tinyuf2> BOARD=... BOARD_DIR= ... all`
This works fine, but is not overly obvious. I agree to abandon the idea of a shorter name "APP_START" in my PR #162. But I would prefer to set the app start using `make ... BOARD_FLASH_APP_START=0x08004000 all`. However this requires some changes to tinyuf2 makefiles.
=> Allow for a custom application start vector on stm32 boards

.github/workflows/build_arm.yml, .gitmodules, ports/stm32l4/Makefile, ports/stm32l4/README.md, ports/stm32l4/apps/erase_firmware/Makefile, ports/stm32l4/board_flash.c, ports/stm32l4/boards.c, ports/stm32l4/boards.h, ports/stm32l4/boards/swan_r5/board.c, ports/stm32l4/boards/swan_r5/board.h, ports/stm32l4/boards/swan_r5/board.mk, ports/stm32l4/linker/stm32l4.ld, ports/stm32l4/stm32l4xx_hal_conf.h, ports/stm32l4/tusb_config.h
This PR implements a port of tinyuf2 to the STM32L4 family, specifically the L4R5. 
The code has been tested for a few months and is considered fairly stable. 
The implementation is mostly a copy and paste of the existing STM32F4 port, updated with the most recent changes.  In the longer run, the common elements of F4 and L4 ports may benefit from being merged to avoid code duplication. 
I tested the bootloader using this test plan on Swan R5:
* start with a fully erased device
* use dfu-util to load the bootloader binary and power-cycle the device
* verify the SWANBOOT drive appears
* copy a UF2 file to the drive (e.g. circuitpython)
* after the file has copied, verify that the CIRCUITPY drive appears
* double-tap RESET and verify the SWANBOOT drive appears. 
* single-tap RESET and …
=> stm32l4 support

.github/workflows/build_arm.yml
- use carlosperate/arm-none-eabi-gcc-action for toolchain installation
- also add linkermap for size analysis
=> migrate installing toolchain to Action gcc

.github/workflows/build_esp32.yml, ports/espressif/boards/waveshare_esp32_s2_pico_lcd/board.cmake, ports/espressif/boards/waveshare_esp32_s2_pico_lcd/board.h, ports/espressif/boards/waveshare_esp32_s2_pico_lcd/sdkconfig
Adds support for the Waveshare ESP32-S2-Pico-LCD Board with USB PID from Espressif: [Espressif USB customer-allocated PID repository](https://github.com/espressif/usb-pids/blob/b39d288d4821bedfb589b7ec3cc8a3e2779e6237/allocated-pids.txt#L275)
=> Add waveshare ESP32-S2-Pico-LCD

ports/espressif/boards/cytron_maker_feather_aiot_s3/board.h
I'm sorry, just noticed that the length for volume label is > 11 character in #244.
By the way, GPIO 39 is high when entering UF2 bootloader. Is that normal?
=> Reduced the length for volume label.

.github/workflows/build_esp32.yml, ports/espressif/boards/bpi_picow_s3/board.cmake, ports/espressif/boards/bpi_picow_s3/board.h, ports/espressif/boards/bpi_picow_s3/sdkconfig
Support double reset to tinyUF2.
PID from Espressif.
=> Add BananaPi BPI-PicoW-S3 board.

.github/workflows/build_esp32.yml, ports/espressif/boards/espressif_esp32s3_box/board.cmake, ports/espressif/boards/espressif_esp32s3_box/board.h, ports/espressif/boards/espressif_esp32s3_box/sdkconfig
- PID from Espressif: https://github.com/espressif/usb-pids/blob/main/allocated-pids-espressif-devboards.txt#L12
- Link goes to the github repo: https://github.com/espressif/esp-box
- Checked that the side "boot mode" button can get into UF2 bootloader
- Successfully installed Circuitpython with it
This does not include the `lite` version, don't know if it can just use the same build.
=> Add Espressif ESP32-S3 BOX

.github/workflows/build_esp32.yml
latest idf release v4.4 has issue generating image that couldn't enumerate on some specific S3 boards. It is probably an bug within IDF. This PR switch docker image from `release-v4.4` to `v4.4.3` as walkaround to fix #268
=> switch ci docker image to v4.4.3

ports/stm32f3/boards.c
-----------
Was required for running `qmk_firmware` on top of the bootloader. Without this change it just produced:
```
[142696.720934] usb usb3-port2: attempt power cycle
[142697.190853] usb 3-2: new full-speed USB device number 117 using xhci_hcd
[142697.191129] usb 3-2: Device not responding to setup address.
[142697.397654] usb 3-2: Device not responding to setup address.
[142697.604181] usb 3-2: device not accepting address 117, error -71
[142697.727445] usb 3-2: new full-speed USB device number 118 using xhci_hcd
[142697.727746] usb 3-2: Device not responding to setup …
```
=> Fix stm32f3 application jump

.github/workflows/build_esp32.yml
-----------
This modifies the GitHub actions so that release files are uploaded to Amazon S3. I was unable to test this in my own repo. I already set up the AWS secrets, so this should work. I'll do a release to test after this is merged.
If the test works, then #277 should be done.
=> Update ESP32 GitHub Actions to upload to Amazon S3

.github/workflows/build_esp32.yml
After testing #278, I realized it was uploading everything to a file called `esp32` instead of using that as a folder. This fixes that issue. Otherwise, the rest of the testing worked perfectly.
=> Fix pathname for AWS uploads

.github/workflows/build_esp32.yml
I realized while #279 did indeed fix the issue with it using the filename instead of the folder name, it was missing the release tag. This fixes that issue and I'd be surprised if another follow-up PR is needed.
=> Add release tag to pathname for AWS uploads

ports/stm32l4/boards/swan_r5/board.c
-----------
fix: Increases the drive strength of 32kHz external crystal for the Swan R5 board in line with calculations specified in ST AN2867 sections 3.3, 3.4, and STM32L4 datasheet DS12023 Table 58. LSE oscillator characteristics.
The drive strength RCC_LSEDRIVE_LOW is marginal for the 32kHz crystal oscillator stability, and RCC_LSEDRIVE_MEDIUMLOW meets the calculated drive strength with a small margin for parasitic capacitance.
=> fix: Increases the drive strength of 32kHz external crystal

ports/rules.mk, ports/stm32f3/Makefile, ports/stm32f4/Makefile, ports/stm32f4/boards/stm32f401_blackpill/board.mk, ports/stm32f4/boards/stm32f411ce_blackpill/board.mk, ports/stm32l4/Makefile
* Support erase for `dfu-util`
* Moved to common location to avoid duplication
* Allow use of `st-flash` CLI as an alternative to `STM32_Programmer_CLI`
=> Refactor STM32 flashers

.github/workflows/build_arm.yml, ports/mimxrt10xx/Makefile, ports/mimxrt10xx/README.md, ports/mimxrt10xx/boards.c, ports/mimxrt10xx/boards/teensy40/README.md, ports/mimxrt10xx/boards/teensy40/board.h, ports/mimxrt10xx/boards/teensy40/board.mk, ports/mimxrt10xx/boards/teensy40/clock_config.c, ports/mimxrt10xx/boards/teensy40/clock_config.h, ports/mimxrt10xx/boards/teensy40/flash_config.c, ports/mimxrt10xx/boards/teensy41/README.md, ports/mimxrt10xx/boards/teensy41/board.h, ports/mimxrt10xx/boards/teensy41/board.mk, ports/mimxrt10xx/boards/teensy41/clock_config.c, ports/mimxrt10xx/boards/teensy41/clock_config.h, ports/mimxrt10xx/boards/teensy41/flash_config.c, ports/mimxrt10xx/port.mk, ports/mimxrt10xx/tusb_config.h, ports/rules.mk
**NOTE:  I don't know the appropriate VID/PID -- It's currently using the 1060_evk settings and not the teensy settings.  Not sure which to use**
-----------
This commit adds support for the Teensy 4.0 and 4.1 boards.
It modifies the ports/mimxrt10xx/tusb_config.h and boards.c so that either USB port 0 or usb port 1 can be used.  This is useful for any IMXRT1062 based board.  Though less useful for the teensy 4.0 because it doens't have that port pinned out.
The discussion of this PR is here: https://github.com/adafruit/tinyuf2/discussions/285
=> Teensy 4.0 and 4.1 support

ports/mimxrt10xx/boards.h
For the i.MX RT boards, the current BOARD_FLASH_APP_START is fixed at flash_base + 0xC000.  However it is sometimes useful to put the application in a different memory location.  This patch allows the board.h to configure the app start address.
=> Allow board.h to configure BOARD_FLASH_APP_START

ports/mimxrt10xx/boards.c
-----------
The LED write routine is meant to take a value between 0 for off and 255 for full brightness. the current 10xx port treats 0 as off, and anything else as on when dealing with non-PWM leds.  This creates a case where the LED is on virtually all the time, except for a tiny blink off every 256 timer intervals. 
This fix turns the LED on for `(value >= 128)`  and off for (value < 128), and makes the LED blinking look correct.
=> imxrt10xx: fix LED blinking

src/board_api.h, src/main.c
-----------
Some custom i.MX boards require per board setup.  Currently, I don't see a mechanism for a specific board to have a setup call.
As a specific example, For example, on the i.MX RT 1011, if you happen to have the boot LED on `GPIO_AD_02`, you might need to custom configure `GPR26` in order for it to work with the GPIO configuration you want to use.   
Additionally, there are lots of other potential reasons you might want to do some setup in `boards/<board_name>`.
This patch adds `#ifdef BOARD_INIT_POST_HOOK `, and if it's defined, then `board_init_post_hook()` will be called at the end of `board_init()`.
=> Allow per-board custom init, teardown, and validate hooks

.github/workflows/build_esp32.yml, ports/espressif/boards/m5stack_atoms3_lite/board.cmake, ports/espressif/boards/m5stack_atoms3_lite/board.h, ports/espressif/boards/m5stack_atoms3_lite/sdkconfig
Add [M5Stack AtomS3 Lite](https://shop.m5stack.com/products/atoms3-lite-esp32s3-dev-kit) board
VID & PID comes from EspressIf pids repository: [commit](https://github.com/espressif/usb-pids/commit/b5aee454d64b1266796a8ebf40eb36c8f796ff45)
=> Add M5Stack AtomS3 board

ports/espressif/README.md
Add "ESP32-S3" statement to README of ports/espressif page.
=> Add "ESP32-S3" Statement to Readme

ports/espressif/partitions-8MB.csv
exposed-by-bootloaders)
-----------
use 'app' instead of 0, change should not effect functionality, however makes partition table more consistent with the espressif docs!
https://docs.espressif.com/projects/esp-idf/en/v4.1.4/api-guides/partition-tables.html#type-field
Please describe your proposed Pull Request and it's impact.
=> SUKU use 'app' type field instead of numeric 0

.github/workflows/build_esp32.yml, ports/espressif/boards/circuitart_zero_s3/board.cmake, ports/espressif/boards/circuitart_zero_s3/board.h, ports/espressif/boards/circuitart_zero_s3/sdkconfig
link to VID/PID 
https://github.com/espressif/usb-pids
USB_VID = 0x303A - USB_PID = 0x80DC | CircuitArt FeatherS3 - UF2 Bootloader
board has been added to /.github/workflows 
UF2 board id info
#define UF2_BOARD_ID             "ESP32S3-Zero-R1"
#define UF2_VOLUME_LABEL         "ZEROS3BOOT"
#define UF2_INDEX_URL            "https://github.com/CircuitART"
=> pull request for new esp32s3 dev board 

ports/espressif/partitions-16MB.csv
same as #308 but for 16MB partition table
=> SUKU use 'app' type field instead of numeric 0 (16MB partition table)

ports/espressif/partitions-4MB.csv
same as #308 but for 4MB partition table
=> SUKU use 'app' type field instead of numeric 0 (4MB partition table)

README.md, cmake/family_support.cmake, cmake/toolchain/arm_gcc.cmake, ports/stm32f3/CMakeLists.txt, ports/stm32f3/apps/self_update/CMakeLists.txt, ports/stm32f3/board_flash.c, ports/stm32f3/boards.c, ports/stm32f3/boards.h, ports/stm32f3/boards/stm32f303disco/board.h, ports/stm32f3/linker/stm32f3_boot.ld, ports/stm32f3/tusb_config.h, ports/stm32f4/board_flash.c, src/board_api.h, src/main.c, src/tinyuf2.cmake, src/usb_descriptors.c
Slight complication on the implementation compared to F4 as `HAL_FLASH_OB_Launch` resets the MCU. Without specific logic to handle this case the self-updater gets into a bit of a spin.
1. self-update calls `board_flash_protect_bootloader(false)`
2. MCU resets
3. bootloader main then runs `board_flash_protect_bootloader(true)`
4. MCU resets
5. goto 1
Catching the reset reason allows the bootloader to re-run the self-updater with the now unlocked write protection.
=> Implement stm32f3 bootloader protection

ports/stm32l4/Makefile, ports/stm32l4/README.md, ports/stm32l4/board_flash.c, ports/stm32l4/boards.c, ports/stm32l4/boards.h, ports/stm32l4/port.mk
STM32L4 support has been mentioned a few times on the QMK Discord. Eventually targeting single-bank MCU like the STM32L432, there are a few assumptions on flash layout to unpick. 
Before submitting those changes, I figured it was worth a pass to tidy a few areas up so that its more consistent with the F3 and F4 port.
=> Minor alignment of STM32L4 port

.github/workflows/build_esp32.yml, ports/espressif/boards/m5stack_atoms3/board.cmake, ports/espressif/boards/m5stack_atoms3/board.h, ports/espressif/boards/m5stack_atoms3/sdkconfig, ports/espressif/boards/m5stack_atoms3_lite/board.h
Add [M5Stack AtomS3 ](https://shop.m5stack.com/products/atoms3-dev-kit-w-0-85-inch-screen) board
VID & PID comes from EspressIf pids repository
Also fixed UF2_BOARD_ID for AtomS3 Lite board. Now IDs are:
- AtomS3 Lite -> ESP32S3-AtomS3Lite-01
- AtomS3 -> ESP32S3-AtomS3-01
=> M5stack atoms3

.github/workflows/build_esp32.yml, ports/espressif/boards/yd_esp32_s3_n16r8/board.cmake, ports/espressif/boards/yd_esp32_s3_n16r8/board.h, ports/espressif/boards/yd_esp32_s3_n16r8/sdkconfig, ports/espressif/boards/yd_esp32_s3_n8r8/board.cmake, ports/espressif/boards/yd_esp32_s3_n8r8/board.h, ports/espressif/boards/yd_esp32_s3_n8r8/sdkconfig
-----------
Adding YD-ESP32-S3. I should have long done this already.
As a note, I am not affiliated with VCC-GND.
=> Add YD-ESP32-S3

.github/workflows/build_esp32.yml, ports/espressif/README.md, ports/espressif/boards/seeed_xiao_esp32s3/board.cmake, ports/espressif/boards/seeed_xiao_esp32s3/board.h, ports/espressif/boards/seeed_xiao_esp32s3/sdkconfig
=> board: add support for seeed xiao esp32s3

ports/espressif/boards/adafruit_camera_esp32s3/board.h, ports/espressif/boards/boards.c
There were several bits of code that needed to be revised so that the LCD display works on the adafruit-camera-esp32s3:
* the backlight has to be turned on through the I/O expander, which is an AW9523 type
* the VSCSAD register value was wrong, making the top part of the screen corrupt
This is tested on PyCam Rev C board.
=> adafruit-camera-esp32s3: make LCD work

.github/workflows/build_esp32.yml, ports/espressif/boards/m5stack_atoms3u/board.cmake, ports/espressif/boards/m5stack_atoms3u/board.h, ports/espressif/boards/m5stack_atoms3u/sdkconfig
-----------
Add M5Stack AtomS3U board. It is similar to [AtomS3 Lite board](https://github.com/adafruit/tinyuf2/tree/master/ports/espressif/boards/m5stack_atoms3_lite) that is already added and share same controller and basic pinout (button and LED).
USB IDs taken from https://github.com/espressif/usb-pids/blob/60f612f5e2e177104382a009e7b787fc463c18d1/allocated-pids.txt#L400C3-L400C7
Datasheet: https://docs.m5stack.com/en/core/AtomS3U
I am not associated with M5Stack.
=> Add M5Stack AtomS3U

.github/workflows/build_esp32.yml, ports/espressif/README.md, ports/espressif/boards/es3ink/board.cmake, ports/espressif/boards/es3ink/board.h, ports/espressif/boards/es3ink/sdkconfig
[Link](https://github.com/pidcodes/pidcodes.github.com/pull/862)
-----------
Add ES3ink board
=> Add ES3ink board

ports/espressif/boards/bpi_leaf_s3/board.h
New BPI-Leaf-S3 v1.1 version support double-clicking the reset button to enter the UF2 bootloader.
=> Update  bpi_leaf_s3

.github/workflows/build_esp32.yml, ports/espressif/boards/magiclick_s3_n4r2/board.cmake, ports/espressif/boards/magiclick_s3_n4r2/board.h, ports/espressif/boards/magiclick_s3_n4r2/sdkconfig, ports/espressif/components/lcd/include/lcd.h, ports/espressif/components/lcd/lcd.c
-----------
add display gc9107
add board magiclick_s3_n4r2
[Board Repo](https://github.com/MakerM0/MagiClick-esp32s3)
[VID&PID](https://github.com/espressif/usb-pids/blob/60f612f5e2e177104382a009e7b787fc463c18d1/allocated-pids.txt#L436)
=> add board magiclick_s3_n4r2  &  display gc9107

ports/espressif/boards/lilygo_ttgo_t_twr_plus/board.cpp
-----------
Upcoming revision V2.1 of the LilyGO T-TWR board uses a little bit different NeoPixel power enable signal.
This PR makes the TinyUF2 bootloader to be compatible both with version 2.0 and version 2.1 of the product.
=> minor update of ESP32-S3 BSP for LilyGO T-TWR Plus v2.x

.github/workflows/build_arm.yml
Remove linkermap usage, since some pip package is missing which cause it failed to install
=> remove linkermap in ci since it failed to install

.github/workflows/build_esp32.yml, ports/espressif/boards/waveshare_esp32_s3_pico/board.cmake, ports/espressif/boards/waveshare_esp32_s3_pico/board.h, ports/espressif/boards/waveshare_esp32_s3_pico/sdkconfig
Request to add support for Waveshare ESP32 S3 Pico.
Circuitpython Support [added](https://github.com/adafruit/circuitpython/pull/8352).
VID/PID is provided by [Espressif](https://github.com/espressif/usb-pids/blob/main/allocated-pids.txt) 
```
0x81A2 | Waveshare ESP32-S3-Pico - UF2 Bootloader
0x81A3 | Waveshare ESP32-S3-Pico - CircuitPython
```
=> Add Waveshare ESP32 S3 Pico

ports/espressif/boards/boards.c, ports/espressif/components/tinyusb_src/tusb_config.h, ports/k32l2/tusb_config.h, ports/lpc55/tusb_config.h, ports/mimxrt10xx/tusb_config.h, ports/stm32f4/tusb_config.h, ports/stm32h7/tusb_config.h, ports/stm32l4/tusb_config.h, ports/template_port/tusb_config.h, src/main.c, src/usb_descriptors.c, tools/touch1200.py
- remove HID since not used
- enable CDC support for esp32sx, which support touch1200 to reboot to bootrom, tested with s2,s3. fix #232
=> Remove hid add cdc

ports/espressif/boards/boards.c
more change to improve esp32sx touch1200 to bootrom
=> esp32 force dmdp reset

ports/espressif/README.md
*fixes* the example in the *usage* section in the README.md for the expressif borads - 
as at least i needed a static cast to `esp_reset_reason_t` to compile cleanly..
=> esp23 fix README.md reboot_to_uf2

.github/workflows/build_arm.yml, ports/stm32f4/boards/sparkfun_micromod_stm32/board.h, ports/stm32f4/boards/sparkfun_micromod_stm32/board.mk
-----------
Add support for the SparkFun MicroMod STM32 processor.
VID+PID pulled from thread: https://github.com/adafruit/tinyuf2/pull/191#issuecomment-1033064414
=> Add Sparkfun MicroMod STM32

ports/espressif/components/bootloader/subproject/main/bootloader_start.c
UF2_DETECTION_DELAY_MS can be set to zero when PIN_BUTTON_UF2 is not GPIO0 on ESP32. This causes the board to boot application firmware instantly if the PIN_BUTTON_UF2 is not pulled low by pressing the boot button. The problem is that the RGB LEDs still turn purple momentarily indicating that the bootloader is waiting for button press. This causes unwanted flash of the LEDs.  In this PR code skips board_led_on() is only called if UF2_DETECTION_DELAY_MS>0 condition is met!
Please note that for compatibility reasons if PIN_DOUBLE_RESET_RC is defined then board_led_on() will always be called regardless of UF2_DETECTION_DELAY_MS!
=> Only show purple waiting color on led if UF2_DETECTION_DELAY_MS is not zero

.github/workflows/build_esp32.yml, ports/espressif/boards/lolin_s3_mini/board.cmake, ports/espressif/boards/lolin_s3_mini/board.h, ports/espressif/boards/lolin_s3_mini/sdkconfig
Add support for Lolin S2-Mini board
PID was already allocated in Espressif USB-PIDS repository
0x8169 | LOLIN S3 Mini - UF2 Bootloader
=> Add lolin s3 mini

ports/espressif/boards/m5stack_stamps3/board.h
-----------
Fixes.
The stamp is used for the cardputer. Testing on that.
Under circuitpython the panel works correctly, but not under uf2, this PR fixes that.
When sending a reset, the board sometimes entered uf2 mode, this is fixed by disabling double reset.
Additionally improved the branding a bit cuz it annoys me seeing wrong info.
=> Fix backlight, reset entering uf2 and correct branding info for M5Stamp S3

ports/espressif/boards/lilygo_twatch_s3/board.cmake, ports/espressif/boards/lilygo_twatch_s3/board.h, ports/espressif/boards/lilygo_twatch_s3/sdkconfig
-----------
Board added: LILYGO T-Watch-S3
~~Pending~~ USB VID PR: https://github.com/espressif/usb-pids/pull/168
CircuitPython PR: https://github.com/adafruit/circuitpython/pull/9480
The display is working as intended, however I do not know how to define rotation.
Note: I am not affiliated with the manufacturer.
=> Add LILYGO T-Watch-S3

ports/espressif/boards/unexpectedmaker_omgs3/board.cmake, ports/espressif/boards/unexpectedmaker_omgs3/board.h, ports/espressif/boards/unexpectedmaker_omgs3/sdkconfig, ports/espressif/boards/unexpectedmaker_rgbtouch_mini/board.cmake, ports/espressif/boards/unexpectedmaker_rgbtouch_mini/board.h, ports/espressif/boards/unexpectedmaker_rgbtouch_mini/sdkconfig, ports/espressif/boards/unexpectedmaker_tinywatchs3/board.cmake, ports/espressif/boards/unexpectedmaker_tinywatchs3/board.h, ports/espressif/boards/unexpectedmaker_tinywatchs3/sdkconfig
Added my new OMGS3
Added my new RGB Touch Mini
Added my TinyWATCH S3
TinyWATCH S3 doesn't have a status LED or RGB LED, so I commented out the DATA and POWER pins, and set the number of RGB LEDs to 0.
I hope that is the correct way to handle this use case. It seems to work ok, but I am not sure if there's an alternate way to handle no status LED.
PIDs/VID supplied by Espressif
=> Added 3 new Unexpected Maker boards

.github/actions/setup_toolchain/action.yml, .github/actions/setup_toolchain/espressif/action.yml, .github/workflows/build.yml, .github/workflows/build_ghostfat.yml, .github/workflows/build_util.yml, ports/espressif/CMakeLists.txt, ports/espressif/README.md, ports/espressif/boards/boards.c, ports/espressif/components/bootloader/subproject/main/bootloader_start.c
This partly fixes an issue https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/436, when S3 is enumerated as USB JTAG while waiting for 2nd reset
- only attempt to wait for 2nd reset if reset by by by power on (En/nRST pin)
- temporarily change USB phy to OTG while waiting for 2nd reset to prevent S3 is enumerated with USB JTAG.
- also bump up idf to v5.1.4 to match latest arduino-esp32 idf version
- some tweak to ci build
=> prevent S3 enumerated as USB JTAG while waiting for 2nd reset

ports/espressif/components/tinyusb_src/CMakeLists.txt
- switch esp32 dcd driver to use dwc2
- update tinyusb to commit 3eea46056ea20aa12b73eea7c01d6c6e5b2d490a
=> update tinyusb  and switch esp32 dcd driver to use dwc2

ports/mimxrt10xx/boards/arch_mix_1052/board.h, ports/mimxrt10xx/boards/arch_mix_1052/board.mk, ports/mimxrt10xx/boards/arch_mix_1052/clock_config.c, ports/mimxrt10xx/boards/arch_mix_1052/clock_config.h, ports/mimxrt10xx/boards/arch_mix_1052/flash_config.c, ports/mimxrt10xx/boards/makerdiary_rt1011/board.h, ports/mimxrt10xx/boards/makerdiary_rt1011/board.mk, ports/mimxrt10xx/boards/makerdiary_rt1011/clock_config.c, ports/mimxrt10xx/boards/makerdiary_rt1011/clock_config.h, ports/mimxrt10xx/boards/makerdiary_rt1011/flash_config.c, ports/mimxrt10xx/boards/olimex_rt1010/board.h, ports/mimxrt10xx/boards/olimex_rt1010/board.mk, ports/mimxrt10xx/boards/olimex_rt1010/clock_config.c, ports/mimxrt10xx/boards/olimex_rt1010/clock_config.h, ports/mimxrt10xx/boards/olimex_rt1010/flash_config.c
Boards:
- Seed Arch Mix RT1052
- Olimex RT1011
- Makerdiary RT1011 Nano Kit
All sets differ only slightly from the respective imxrt10xx-evk files. Major changes are flash size and LED pin. All have been tested with theses boards.
=> ports/mimxrt10xx/boards: Add board files for Seeed ARch Mix, Olimex RT1011 and Makerdiary RT1011 Nano Kit..

ports/espressif/boards/lilygo_tdeck/board.cmake, ports/espressif/boards/lilygo_tdeck/board.h, ports/espressif/boards/lilygo_tdeck/sdkconfig
https://github.com/espressif/usb-pids/blob/main/allocated-pids.txt
-----------
Add LILYGO T-Deck. Display works as intended.
=> Add LILYGO T-Deck

ports/espressif/boards/generic_esp32s3_super_mini/board.cmake, ports/espressif/boards/generic_esp32s3_super_mini/board.h, ports/espressif/boards/generic_esp32s3_super_mini/sdkconfig
-----------
Adds support for a generic "ESP32-S3 Super Mini" dev board.
This board can be found on Aliexpress and other chinese marketplaces, but seemingly there is no actual info on the original creator or manufacturer.
The style is similar to the C3-variant, which seems to be a clone of the waveshare ESP32-C3 Super Mini. But there is no comparible S3-Variant.
The only info I could find, that is not a direct shop page, is on [this site](https://www.nologo.tech/product/esp32/esp32s3supermini/esp32S3SuperMini.html).
Because of this I propose the "generic" term, which I also used to …
=> Add Definition for generic ESP32-S3 Super Mini Board

ports/mimxrt10xx/boards/arch_mix_1052/flash_config.c, ports/mimxrt10xx/boards/imxrt1010_evk/flash_config.c, ports/mimxrt10xx/boards/imxrt1015_evk/flash_config.c, ports/mimxrt10xx/boards/imxrt1020_evk/flash_config.c, ports/mimxrt10xx/boards/imxrt1040_evk/flash_config.c, ports/mimxrt10xx/boards/imxrt1050_evkb/flash_config.c, ports/mimxrt10xx/boards/imxrt1060_evk/flash_config.c, ports/mimxrt10xx/boards/imxrt1064_evk/flash_config.c, ports/mimxrt10xx/boards/makerdiary_rt1011/flash_config.c, ports/mimxrt10xx/boards/metro_m7_1011/flash_config.c, ports/mimxrt10xx/boards/metro_m7_1011_sd/flash_config.c, ports/mimxrt10xx/boards/olimex_rt1010/flash_config.c
CLK is increased to the highest value defined in the data sheets of the respective flash device. The previous values of 60MHz and 30MHz reduce the speed of the APP. Tested with:
- arch_mix_1052
- imxrt1010_evk
- imxrt1015_evk
- imxrt1020_evk
- makerdiary_rt1011
- metro_m7_1011
- olimex_rt1010
=> mimxrt10xx/boards: Increase the flash CLK frequency.

ports/mimxrt10xx/boards/olimex_rt1010/flash_config.c
The settings for the initialization sequence of my last PR were not the right ones. Instead of the W25Q16 flash listed initially in the first Olimex documentation, the production boards now use an EN25Q16B-104HIP chip, which needs different arguments to enable quad mode. With the existing arguments, the flash may get write locked.
Tested with an Olimex RT1010Py board.
P.S.: In case the flash got write locked can then be unlocked using the flash-sfdp mode for uploading the UF2 bootloader.
=> mimxrt10xx/boards/olimex_rt1010/flash_config.c: Fix flash settings for the init sequence.

.github/workflows/codeql.yml
Per email from github, the 20.04 runners will soon be removed. switch up to the latest github ubuntu version instead.
-----------
Please describe your proposed Pull Request and it's impact.
=> Avoid deprecated ubuntu 20.04 runners

ports/espressif/boards/waveshare_esp32_s3_matrix/board.cmake, ports/espressif/boards/waveshare_esp32_s3_matrix/board.h, ports/espressif/boards/waveshare_esp32_s3_matrix/sdkconfig
-----------
This pull request adds support for [Waveshare's ESP32-S3-Matrix development board](https://www.waveshare.com/wiki/ESP32-S3-Matrix). The files added were based on the preexisting port for Waveshare's ESP32-S3-Zero board because they are very similar. This board uses USB VID 0x303A (Espressif) and PID 0x826F from line 631 of [Espressif's allocated PIDs list](https://github.com/espressif/usb-pids/blob/main/allocated-pids.txt).
=> Added support for the Waveshare ESP32-S3-Matrix board

ports/espressif/README.md, ports/espressif/boards/lilygo_tdongle_s3/board.cmake, ports/espressif/boards/lilygo_tdongle_s3/board.h, ports/espressif/boards/lilygo_tdongle_s3/sdkconfig
-----------
Adding support for the [LILYGO T-Dongle-S3](https://github.com/Xinyuan-LilyGO/T-Dongle-S3/).
Allocated PID:
- [0x82C3 | LILYGO T-Dongle-S3 - UF2 Bootloader](https://github.com/espressif/usb-pids/pull/220)
=> Add support for LILYGO T-Dongle S3

ports/espressif/boards/lilygo_tqt_pro_nopsram/board.cmake, ports/espressif/boards/lilygo_tqt_pro_nopsram/board.h, ports/espressif/boards/lilygo_tqt_pro_nopsram/sdkconfig, ports/espressif/boards/lilygo_tqt_pro_psram/board.cmake, ports/espressif/boards/lilygo_tqt_pro_psram/board.h, ports/espressif/boards/lilygo_tqt_pro_psram/sdkconfig
There are two variants of the Lilygo T-QT Pro. I only own one but the difference is the ram/flash setup (N8 and N4R2 version). I used the VID/PID requested by @tyeth who didn't get to adding the board at the time.
It has a display, and no status LED.
PID: https://github.com/espressif/usb-pids/pull/80
Product page: https://lilygo.cc/products/t-qt-pro
Github page: https://github.com/Xinyuan-LilyGO/T-QT
Note that the non-pro are no longer available on Lilygo's site, but should be compatible with this.
=> Add Lilygo T-QT pro boards, N4R2 and N8

ports/espressif/boards/waveshare_esp32_s3_touch_lcd_2/board.cmake, ports/espressif/boards/waveshare_esp32_s3_touch_lcd_2/board.h, ports/espressif/boards/waveshare_esp32_s3_touch_lcd_2/sdkconfig
The board is Waveshare part No ESP32-S3-Touch-LCD-2
_ESP32-S3 2inch Capacitive Touch Display Development Board_
https://www.waveshare.com/esp32-s3-touch-lcd-2.htm?sku=29667
PID requested: https://github.com/espressif/usb-pids/pull/228
=> add Waveshare ESP32S3 Touch LCD 2

.github/workflows/build_util.yml, ports/espressif/CMakeLists.txt, ports/espressif/Makefile, ports/espressif/apps/self_update/CMakeLists.txt, ports/espressif/boards/adafruit_feather_esp32s3/sdkconfig, ports/espressif/boards/adafruit_feather_esp32s3_reverse_tft/sdkconfig, ports/espressif/boards/adafruit_feather_esp32s3_tft/sdkconfig, ports/espressif/boards/adafruit_qtpy_esp32s3_n4r2/sdkconfig, ports/espressif/boards/deneyap_kart_1a_v2/sdkconfig, ports/espressif/boards/espressif_esp32s3_devkitc_1/board.h, ports/espressif/boards/lilygo_tqt_pro_psram/sdkconfig, ports/espressif/boards/lolin_s3_mini/sdkconfig, ports/espressif/boards/magiclick_s3_n4r2/sdkconfig, ports/espressif/boards/waveshare_esp32_s3_matrix/sdkconfig, ports/espressif/boards/waveshare_esp32_s3_zero/sdkconfig
* Updated the partition table filenames from `partitions-4MB.csv` to `partitions-4MB-noota.csv` for multiple boards, including `adafruit_feather_esp32s3`, `adafruit_feather_esp32s3_reverse_tft`, `adafruit_feather_esp32s3_tft`, `adafruit_qtpy_esp32s3_n4r2`, `deneyap_kart_1a_v2`, `lilygo_tqt_pro_psram`, `lolin_s3_mini`, `magiclick_s3_n4r2`, `waveshare_esp32_s3_matrix`, and `waveshare_esp32_s3_zero`. [[1]](diffhunk://#diff-62166c16d9852bb91dff61b8609e68d4a496fe0a5944c9473520df8c94f6aad2L4-R4) [[2]](diffhunk://#diff-4ec656212ee487c916db4217649f2de7a5f1f808dd79f8577cc61797a819d7e9L4-R4)
* [`ports/espressif/boards/espressif_esp32s3_devkitc_1/board.h`](diffhunk://#diff-715ec43d3b71766f21d052069ce94e43b45da93cccf487e1437ba089a32a9bb2L46-R46): Changed the Neopixel data pin from 48 to 38.
* …
=> Change s3 4m partition to noota

src/usb_descriptors.c
-----------
Updated the USB Descriptors to accommodate MCUs where the endpoint number can only be used in a single direction.  These devices are identified in TinyUSB by the TUD_ENDPOINT_ONE_DIRECTION_ONLY definition.  This update is in preparation for utilizing the TinyUF2 project with Analog Devices MAX32 MCUs, and contributing a port to those parts.
=> Support Devices with One Direction Endpoints

ports/espressif/CMakeLists.txt
- include partition-table-ota.bin to artifact, rename to combined-ota.bin for consistency (previously combined_ota.bin) 
- include flash_args to artifact, to make it easier for user to know which address to flash for each binaries
=> include flash_args to artifact

.github/workflows/build_util.yml
- Fixes #452
During a release
- Change the upload location on S3 for the `tinyuf2*.zip` and `update-tinyuf2*.uf2` to a board-specific directory. The upload path used to be, for example:
`s3://adafruit-circuit-python/bootloaders/esp32/tinyuf2-adafruit_feather_esp32s3-0.32.0.zip`
and now it is
`s3://adafruit-circuit-python/bootloaders/esp32/adafruit_feather_esp32s3/tinyuf2-adafruit_feather_esp32s3-0.32.0.zip`
This groups by board name, and reduces the large number of files at one level in S3.
- Also upload, to the same board directory, the `combined.bin` and, if it exists, the `combined-ota.bin`. The files are renamed to include the board name and version, for example
`tinyuf2-adafruit_feather_esp32s3-0.32.0-combined.bin`
See https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix …
=>  Upload Espressif bootloader .zip and combined*.bin to board-specific  dirs on S3

ports/espressif/boards/heltec_vision_master_t190/board.cmake, ports/espressif/boards/heltec_vision_master_t190/board.h, ports/espressif/boards/heltec_vision_master_t190/sdkconfig
This pull request adds support the the Heltec Vision Master T190 board.
Product: https://heltec.org/project/vision-master-t190
PID: Espressif default 0x303A:0x1001
A comment in board.h shows how to rotate the display if needed.
=> Add support for Heltec Vision Master T190
