partitions.csv

finialize partition table

---

CMakeLists.txt
components/bootloader/project_include.cmake
components/bootloader/subproject/main/CMakeLists.txt
components/bootloader/subproject/main/bootloader_start.c

accidentally overwritten when fixing build with latest IDF

fix 2nd bootloader is overwritten when pulling from IDF

---

.github/workflows/build.yml

Also, add UnexpectedMaker FeatherS2

Upload release assets and build artifacts

---

components/boards/boards.c

fix usb issue with latest idf

---

components/boards/CMakeLists.txt
components/boards/boards.c
components/boards/unexpectedmaker_feathers2/board.h
components/led_strip_spi_apa102/CMakeLists.txt
components/led_strip_spi_apa102/include/led_strip_spi_apa102.h
components/led_strip_spi_apa102/src/led_strip_spi_apa102.c

Could be the cause of the "invalid header: 0x0a324655" issue in the automatic UF2 build.

Wrong pin set for PIN_APA102_DATA for FeatherS2 board.h

---

ports/esp32s2/CMakeLists.txt

fix esp32s2 build/sdkconfig

---

ports/esp32s2/boards/adafruit_magtag_29gray/board.h
ports/esp32s2/boards/adafruit_metro_esp32s2/board.h
ports/esp32s2/boards/boards.c
ports/esp32s2/components/bootloader/subproject/main/bootloader_start.c
src/board_api.h
src/main.c

implement pwm led for esp32s2
also replace soft timer by esp_timer since soft timer cannot run with interval less than 5 ms

Add pwm esp32s2

---

ports/esp32s2/CMakeLists.txt
ports/mimxrt10xx/Makefile
ports/stm32f4/Makefile
src/ghostfat.c
src/uf2.h

add `UF2_VERSION`  using git version & submodule versions to `INFO.txt` file. Partly implement #39

Generate release

---

ports/make.mk
ports/mimxrt10xx/Makefile
ports/stm32f4/Makefile
ports/template_port/Makefile
ports/template_port/board_flash.c
ports/template_port/boards.c
ports/template_port/boards.h
ports/template_port/boards/dummy/board.h
ports/template_port/boards/dummy/board.mk
ports/template_port/tusb_config.h

added template port to allow quickly copy-then-modify to add new port

Add template port

---

ports/mimxrt10xx/boards/imxrt1020_evk/bl_api.c
ports/mimxrt10xx/boards/imxrt1020_evk/bl_api.h
ports/mimxrt10xx/boards/imxrt1020_evk/board.h
ports/mimxrt10xx/boards/imxrt1020_evk/flash_config.c
ports/mimxrt10xx/linker/MIMXRT1021_nor.ld

I added load2ram support for the RT1020 consistent with the RT1060 and RT1010.
This builds, but I do not have hardware to test.

added load2ram support for RT1020

---

src/main.c

Just the small changes needed to make it work. Using this to flash a peripheral.

Fix build on rp2040

---

src/uf2.h

Enable configuration of the ghostfat options via compiler defines.

Allow  >1 sector per cluster

---

.github/workflows/build.yml
ports/lpc55/Makefile
ports/make.mk
ports/mimxrt10xx/Makefile
ports/mimxrt10xx/README.md
ports/mimxrt10xx/board_flash.c
ports/mimxrt10xx/boards.c
ports/mimxrt10xx/boards/imxrt1010_evk/flexspi_nor_flash.c
ports/mimxrt10xx/boards/metro_m7_1011/flexspi_nor_flash.c
ports/mimxrt10xx/flash_nuke/Makefile
ports/mimxrt10xx/flash_nuke/flash_nuke.c
ports/mimxrt10xx/flexspi_nor_flash.h
ports/template_port/boards.c
src/board_api.h

adding flash nuke to build system

add flash nuke-BOARD for iMX RT port

---

src/uf2.h

Add comments for flash size configuration values

---

.github/workflows/build.yml
ports/lpc55/Makefile
ports/make.mk
ports/stm32f4/Makefile
src/CMakeLists.txt

- update tinyusb to latest
- speed up ci by only checkout needed submodules by each board

Optimize ci

---

.gitmodules
ports/lpc55/Makefile
ports/mimxrt10xx/Makefile
ports/mimxrt10xx/port.mk

fix #59 use official NXP MCU SDK as submodules. @nxf58843

Use nxp official sdk

---

.github/workflows/build.yml

Added UM TinyS2 to the build workflow - which I forgot to do pre 4.0 :(

---

.github/workflows/build.yml
ports/stm32f4/boards/stm32f411ce_blackpill/README.txt
ports/stm32f4/boards/stm32f411ce_blackpill/board.h
ports/stm32f4/boards/stm32f411ce_blackpill/board.mk

Successfully tested this new board. This is the same board sold on Adafruit and Aliexpress.
https://www.adafruit.com/product/4877

Add STM32F411CE "Blackpill" board

---

ports/esp32s2/Makefile

This is a single file ready to flash at 0x0, similar to the combined.bin for funhouse (except that combined.bin also has an arduino program baked in)

esp32s2: Add "combined.bin"

---

ports/stm32f3/board_flash.c
ports/stm32f4/board_flash.c

fix -Wcast-align in board_flash stm32f4 f3

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
README.md

template make it easier to report,reproduce and fix bug

Add template form

---

.github/ISSUE_TEMPLATE/bug_report.yml
ports/stm32f4/board_flash.c

should fix #136  take the chance to clean up flashing code. may also fix (or not) #75

fix updating issue with circuipython due to large size

---

README.md
changelog.md
ports/esp32s2/README.md
ports/stm32f4/README.md
ports/stm32f4/board_flash.c
ports/stm32f4/boards/feather_stm32f405_express/board.mk
ports/stm32f4/boards/stm32f401_blackpill/board.mk
ports/stm32f4/boards/stm32f411ce_blackpill/README.txt
ports/stm32f4/boards/stm32f411ce_blackpill/board.h
ports/stm32f4/boards/stm32f411ce_blackpill/board.mk
ports/stm32f4/boards/stm32f411ve_discovery/board.mk

prepare for release 0.5.1

---

ports/esp32s2/README.md
ports/esp32s2/boards/microdev_micro_s2/board.h

Contains some minor updates for board `microS2`. 🙂🚀

Minor updates for board MicroDev microS2

---

ports/make.mk
ports/stm32f3/board_flash.c
ports/stm32f4/board_flash.c

Just some typos I stumbled while debugging stm32f4 for pull request #158

fix typo in comments and missing linefeeds in log messages

---

ports/espressif/boards/adafruit_camera_esp32s2/board.h

@hathach do you know why pin 42 might not be working for RC? its a JTAG pin, not sure if its special...

fix red LED pin

---

.github/workflows/build_esp32.yml
ports/espressif/boards/adafruit_qtpy_esp32s3/board.cmake
ports/espressif/boards/adafruit_qtpy_esp32s3/board.h
ports/espressif/boards/adafruit_qtpy_esp32s3/sdkconfig

QT Py S3 with 4MB flash internal
with RC on pin 10, neopixel on 38

add lil s3

---

.github/workflows/build_esp32.yml
ports/espressif/boards/unexpectedmaker_feathers3/board.cmake
ports/espressif/boards/unexpectedmaker_feathers3/board.h
ports/espressif/boards/unexpectedmaker_feathers3/sdkconfig
ports/espressif/boards/unexpectedmaker_pros3/board.cmake
ports/espressif/boards/unexpectedmaker_pros3/board.h
ports/espressif/boards/unexpectedmaker_pros3/sdkconfig
ports/espressif/boards/unexpectedmaker_tinys3/board.cmake
ports/espressif/boards/unexpectedmaker_tinys3/board.h
ports/espressif/boards/unexpectedmaker_tinys3/sdkconfig

Added my new TinyS3, FeatherS3 and ProS3 boards

---

.github/workflows/build_esp32.yml
ports/espressif/boards/adafruit_feather_esp32s3_nopsram/board.cmake
ports/espressif/boards/adafruit_feather_esp32s3_nopsram/board.h
ports/espressif/boards/adafruit_feather_esp32s3_nopsram/sdkconfig

add s3 feather without psram

---

.github/workflows/build_esp32.yml
ports/espressif/boards/bpi_bit_s2/board.cmake
ports/espressif/boards/bpi_bit_s2/board.h
ports/espressif/boards/bpi_bit_s2/sdkconfig
ports/espressif/boards/bpi_leaf_s2/board.cmake
ports/espressif/boards/bpi_leaf_s2/board.h
ports/espressif/boards/bpi_leaf_s2/sdkconfig
ports/espressif/boards/bpi_leaf_s3/board.cmake
ports/espressif/boards/bpi_leaf_s3/board.h
ports/espressif/boards/bpi_leaf_s3/sdkconfig

Added board IDs: BPI-BIT-S2, BPI-Leaf-S2, BPI-Leaf-S3
All PIDs are from Espressif
Thanks in advance.

Added 3 New BPI Boards

---

ports/mimxrt10xx/linker/MIMXRT1021_ram.ld

Hotfix rt1020ld

---

.github/workflows/build_esp32.yml

oops !
thanks to @makermelissa who noticed it was missing.

Add hiibot_iots2 to build workflow

---

ports/lpc55/Makefile
ports/lpc55/apps/self_update/Makefile
ports/rules.mk
ports/stm32f4/Makefile
ports/stm32f4/README.md
ports/stm32f4/board_flash.c
ports/stm32f4/boards.c
ports/stm32f4/linker/stm32f4_app.ld
ports/stm32f4/linker/stm32f4_boot.ld
ports/stm32f4/port.mk

- implement self-update feature for stm32f4, close #47 
- note this PR does not test with protected bootlaoder just yet #189 , will implement it as separated PR.

Stm32f4 self update

---

.github/workflows/build_arm.yml
.github/workflows/build_esp32.yml
ports/mimxrt10xx/Makefile
ports/rules.mk

include self-update binary for f4 in release

---

.github/workflows/build_esp32.yml
ports/espressif/boards/waveshare_esp32s2_pico/board.cmake
ports/espressif/boards/waveshare_esp32s2_pico/board.h
ports/espressif/boards/waveshare_esp32s2_pico/sdkconfig

Disclaimer: I am not affiliated with Waveshare in any way.
It boots Circuitpython and Ljinux all nice and fine.
The activity led also works (breathing while waiting and blinking on file activity).

Add waveshare ESP32-S2-Pico

---

ports/espressif/boards/adafruit_camera_esp32s2/board.h

rev b pins

---

.github/workflows/build_esp32.yml
ports/espressif/boards/cytron_maker_feather_aiot_s3/board.cmake
ports/espressif/boards/cytron_maker_feather_aiot_s3/board.h
ports/espressif/boards/cytron_maker_feather_aiot_s3/sdkconfig

Added Cytron Maker Feather AIoT S3.

---

.github/workflows/build_esp32.yml
ports/espressif/boards/lilygo_ttgo_tbeam_s3/board.cmake
ports/espressif/boards/lilygo_ttgo_tbeam_s3/board.h
ports/espressif/boards/lilygo_ttgo_tbeam_s3/sdkconfig

BOOT (GPIO0) button to enter into tinyUF2 ;
LED on GPIO6 ;
PID from Espressif.

Add LilyGO T-Beam S3

---

ports/espressif/boards/lilygo_ttgo_tbeam_s3/board.h

*This entire checklist section above can be deleted if all items are checked.*
-----------
1) `UF2_BOARD_ID` is now better compliant with [uf2 specs](https://github.com/microsoft/uf2#files-exposed-by-bootloaders) ;
2) new `UF2_DETECTION_DELAY_MS` constant is set to 1000 milliseconds -
_(see https://github.com/adafruit/tinyuf2/pull/254 for details)_.

minor update of LilyGO T-Beam S3 BSP

---

.github/workflows/build_esp32.yml
ports/espressif/boards/lolin_s3/board.cmake
ports/espressif/boards/lolin_s3/board.h
ports/espressif/boards/lolin_s3/sdkconfig

Add LOLIN S3

---

.github/workflows/build_esp32.yml

fix ci abc order

---

.github/workflows/build_esp32.yml
ports/espressif/README.md
ports/espressif/boards/maker_badge/board.cmake
ports/espressif/boards/maker_badge/board.h
ports/espressif/boards/maker_badge/sdkconfig

-----------
Adding Maker badge board

Add Maker badge board

---

.github/workflows/build_arm.yml
.github/workflows/build_esp32.yml
.github/workflows/build_selftest.yml

- [ X ] Please provide specific title of the PR describing the change
- [ X ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
-----------
Updates CI files to stop using actions using Node.js 12.
Fixes #276

Update CI actions to Node.js 16

---

.github/workflows/build_arm.yml

minor ci update

---

ports/stm32f3/boards.c
ports/stm32f4/board_flash.c
ports/stm32f4/boards.c

Noticed a few things while comparing the two ports after recent changes.

Minor stm32f3/stm32f4 alignment

---

cmake/cpu/cortex-m7.cmake
cmake/toolchain/arm_gcc.cmake
cmake/toolchain/set_flags.cmake
ports/espressif/CMakeLists.txt
ports/mimxrt10xx/CMakeLists.txt
ports/mimxrt10xx/boards/metro_m7_1011/board.cmake
ports/mimxrt10xx/family.cmake
src/tinyuf2.cmake

not fully functional, but adding intial cmake support for imxrt (only).

add init support for cmake

---

ports/mimxrt10xx/boards.c

better drive neopixel with imxrt

update neopixel driver for imxrt

---

ports/espressif/boards/adafruit_camera_esp32s3/board.h
ports/espressif/components/lcd/lcd.c

- DISPLAY_PIN_BL is now optional (not defined or -1)
- fix #325

make DISPLAY_PIN_BL optional (not defined or  -1)

---

.github/workflows/build_esp32.yml
ports/espressif/boards/adafruit_metro_esp32s3/board.cmake
ports/espressif/boards/adafruit_metro_esp32s3/board.h
ports/espressif/boards/adafruit_metro_esp32s3/sdkconfig

fyi @makermelissa @tannewt @PaintYourDragon

new metro s3 with 16mb flash

---

.github/workflows/build_esp32.yml
ports/espressif/boards/unexpectedmaker_nanos3/board.cmake
ports/espressif/boards/unexpectedmaker_nanos3/board.h
ports/espressif/boards/unexpectedmaker_nanos3/sdkconfig

Added support for Unexpected Maker NanoS3.
VID/PID is provided by Espressif

Add Unexpected Maker NanoS3

---

.github/workflows/build_esp32.yml
ports/espressif/boards/unexpectedmaker_bling/board.cmake
ports/espressif/boards/unexpectedmaker_bling/board.h
ports/espressif/boards/unexpectedmaker_bling/sdkconfig

-----------
Add Unexpected Maker [Bling](https://unexpectedmaker.com/shop.html#!/BLING/p/596946493/category=0)
[USB VID/PID Pull Request](https://github.com/espressif/usb-pids/pull/99)

Add Unexpected Maker Bling

---

.github/workflows/build_arm.yml
.github/workflows/build_cmake.yml
.github/workflows/build_esp32.yml
.github/workflows/build_selftest.yml
.github/workflows/codeql.yml
.github/workflows/pre-commit.yml

update tinyusb to get wch ch32 support

Update tinyusb 1fe86f654fdca8a4a555737f34215582a812b481

---

ports/espressif/boards/unexpectedmaker_feathers3_neo/board.cmake
ports/espressif/boards/unexpectedmaker_feathers3_neo/board.h
ports/espressif/boards/unexpectedmaker_feathers3_neo/sdkconfig

Added support for my new FeatherS3 Neo board.
PID/VID supplied by Espressif

Added UM FeatherS3 Neo.

---

ports/espressif/boards/adafruit_vindie_s2/board.cmake
ports/espressif/boards/adafruit_vindie_s2/board.h
ports/espressif/boards/adafruit_vindie_s2/sdkconfig

-----------
Please describe your proposed Pull Request and it's impact.
adding new Adafruit Vindie S2 board. Uses an ESP32-S2

Adding Adafruit Vindie S2 board

---

README.md

update doc add git clone with submodule init

add git clone with submodule init

---

ports/espressif/boards/waveshare_esp32_s3_touch_lcd_169/board.cmake
ports/espressif/boards/waveshare_esp32_s3_touch_lcd_169/board.h
ports/espressif/boards/waveshare_esp32_s3_touch_lcd_169/sdkconfig
ports/espressif/boards/waveshare_esp32s3_lcd_169/board.cmake
ports/espressif/boards/waveshare_esp32s3_lcd_169/board.h
ports/espressif/boards/waveshare_esp32s3_lcd_169/sdkconfig

Board added: ESP32-S3-Touch-LCD-1.69 & ESP32-S3-LCD-1.69
Pending USB VID PR: [espressif/usb-pids/pull/169](https://github.com/espressif/usb-pids/pull/169)

Add Waveshare ESP32-S3-Touch-LCD-1.69 & ESP32-S3-LCD-1.69

---

ports/espressif/boards/adafruit_vindie_s2/board.h

updating neopixel pin for vindie s2

Update vindie s2

---

ports/espressif/boards/circuitart_zero_s3/board.h

This is Revision 2 of a board that has already been added through an older pull request by me.

Revision 2 of CircuitART Zero S3

---

ports/espressif/boards/circuitart_zero_s3/board.h

typo mistake in previous pill request(https://github.com/adafruit/tinyuf2/pull/405)
tft reset should be 40 not 4

Update board.h because of wrong pin in pull request #405 

---

ports/espressif/boards/m5stack_cores3/board.cmake
ports/espressif/boards/m5stack_cores3/board.h
ports/espressif/boards/m5stack_cores3/sdkconfig

Add [M5Stack CoreS3](https://shop.m5stack.com/products/m5stack-cores3-esp32s3-lotdevelopment-kit) board
VID & PID comes from EspressIf pids repository

Add M5Stack CoreS3 board

---

ports/espressif/boards/waveshare_esp32_s3_zero/board.cmake
ports/espressif/boards/waveshare_esp32_s3_zero/board.h
ports/espressif/boards/waveshare_esp32_s3_zero/sdkconfig
src/main.c

-----------
A board already ported to CircuitPython. Got it today, thankfully I don't need to go through the pid-aquiring process.

Add Waveshare ESP32-S3 Zero

---

.github/workflows/build_util.yml

fix release asset with esp without combined-ota.bin

fix release asset with esp without combined-ota.bin
